version: 2
jobs:
  build:
    docker:
      - image: mrszymonello/aspnetcore-build-python
    steps:
      - checkout
      - run: |
          cd software/aspnetcore/src/Api
          dotnet restore
          dotnet build
          cd ../../tests/Api.Tests
          dotnet test
          cd ../../src/Api
          dotnet publish -c Release -o ./bin/Docker
      # build and push Docker image
      - setup_remote_docker      
      - run: |
          cd software/aspnetcore/src/Api
          chmod a+x ../../scripts/docker-publish.sh
          ../../scripts/docker-publish.sh