version: "2"

services:
  api:
    build: ../src/Api
    image: ppm-api
    links:
      - mongo
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'